# Generated by Django 4.2.6 on 2023-11-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('mobilenumber', models.CharField(max_length=255)),
                ('emailid', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
            ],
        ),
    ]
